### ISSUE TITLE
Experts List: Regions Filter

### ISSUE THREAD

**Issue by Gtes** [ita-social-projects/dokazovi-fe#116]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/90

### Task description
Regions Filter section for the Experts

“Region”(“Регіон”) section should contain:

- List of regions
- Possibility of filtering with checkbox

![](https://user-images.githubusercontent.com/71768856/100630325-1692cc00-3333-11eb-95e2-96cf39b9ddb6.png)
![](https://user-images.githubusercontent.com/71768856/100630369-24e0e800-3333-11eb-866f-41eb62a54cae.png)

Click on \/ button should the full region's section come out.
Click on /\ button should the full region's section come back.

### To do 
 - [x] #115  is DONE
 - [x] use https://react-hook-form.com/ if possible
 - [x] GET request for Regions
 - [x] use axios for GET requests 
 - [x] use redux to perform an action, store and get the data to the components.
 - [x] Show/Hide all regions arrow
 - [x] Selected Regions should be displayed at the top.
 - [x] Selected Region should be removed from the top when user deselect it.
 FILTERS:
 - [x] Regions are treated as a form components 
 - [x] on form state change - send a request to GET the updated data.
 - [x] filters are used as query params.
 - [x] use debounceTime for form state change - 500ms

### Estimation
[PERT-Sprint 2](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=212800467)
