### ISSUE TITLE
Experts List: Directions Filter

### ISSUE THREAD

**Issue by Gtes** [ita-social-projects/dokazovi-fe#117]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/90

### Task description
Directions Filter section for the Experts

“Directions”(“Напрямки”) section should contain:

- List of tagged destinations
- Possibility of filtering by tags with checkbox

![](https://user-images.githubusercontent.com/71768856/100629339-d41cbf80-3331-11eb-8d49-610e7b61934e.png)
![](https://user-images.githubusercontent.com/71768856/100629374-e4349f00-3331-11eb-9330-2200fe7b2f6b.png)

Click on \/ button should the full direction's section come out.
Click on /\ button should the full direction's section come back.

### To do 
 - [x] #115  is DONE
 - [ ] use https://react-hook-form.com/ if possible
 - [x] GET request for Directions
 - [x] use axios for GET requests 
 - [x] use redux to perform an action, store and get the data to the components.
 - [x] Show/Hide all regions arrow
 - [x] Selected Directions should be displayed at the top.
 - [x] Selected Direction should be removed from the top when user deselect it.
 FILTERS:
 - [x] Directions are treated as a form components 
 - [x] on form state change - send a request to GET the updated data.
 - [x] filters are used as query params.
 - [x] use debounceTime for form state change - 500ms

### Estimation
[PERT-Sprint 2](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=212800467)
