### ISSUE TITLE
Expert Profile: Expert Materials

### ISSUE THREAD

**Issue by Gtes** [ita-social-projects/dokazovi-fe#118]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/94

### Task description
Show materials for the Expert.

### To do 
- [x] Reuse view from the MainView, from _NewestContainer_:
  - [x] PostsList (old/existing one) - to render posts from props
  - [x] NewestContainer (old/existing one) - to get the posts from the store and send to PostsGridView 
- [x] Get materials for the Expert
- [x] use axios to perform the request
- [x] use redux to perform an action to fetch and store the data 
- [x] LoadMore works
- [x] use separate thunk action to load the data (depending on the Expert)
  - [x] Add spinner to display Loading - use [LoadingInfo.tsx](https://github.com/ita-social-projects/dokazovi-fe/blob/develop/src/lib/components/LoadingInfo.tsx) if possible
- [x] scroll to the last fetched row of the data

### Estimation
[PERT](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=1596292899)
