### ISSUE TITLE
Expert Profile: Expert Info

### ISSUE THREAD

**Issue by Gtes** [ita-social-projects/dokazovi-fe#119]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/94

### Task description
Show information about the Expert.

Expert’s profile:

- Author's picture
- First name, last name
- Position
- Specializations
- Place of work
- Phone number
- Email
- Info about expert

![](https://user-images.githubusercontent.com/71768856/100727953-97070a80-33cf-11eb-84e6-9a6b5032e935.png)

### To do 
- [x] Get info about Expert
- [x] use axios to perform the request
- [x] use redux to perform an action to fetch and store the data
- [x] Click on direction’s value should redirect to "Direction page"
- [x] Add spinner to display Loading - use [LoadingInfo.tsx](https://github.com/ita-social-projects/dokazovi-fe/blob/develop/src/lib/components/LoadingInfo.tsx) if possible

### Estimation
[PERT](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=1596292899)
