### ISSUE TITLE
Expert Profile: Filter for Materials

### ISSUE THREAD

**Issue by Gtes** [ita-social-projects/dokazovi-fe#120]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/94

### Task description
Filter for Expert Materials

### To do 
 - [ ] #118  IS DONE .
 - [ ] use https://react-hook-form.com/ if possible
 - [ ] GET request for entity types (Стаття, Допис ...) 
 - [ ] use axios for GET requests 
 - [ ] use redux to perform an action, store and get the data to the components.
 FILTERS:
 - [ ] post types  are treated as a form components 
 - [ ] on form state change - send a request to GET the updated data.
 - [ ] filters are used as query params.
 - [ ] use debounceTime for form state change - 500ms

### Estimation
[PERT](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=1596292899)
