### ISSUE TITLE
Article: Editor

### ISSUE THREAD

**Issue by calster00** [ita-social-projects/dokazovi-fe#154]
**Story link**
[#122 Story](https://github.com/ita-social-projects/dokazovi-be/issues/122)

### Task description
Create custom Editor component based on one of existing solutions.

It should support:
- Toggling between Underlined, Bold, and Italics text with toolbar buttons
- Normal or Heading text style, changing text style with button
- Toolbar customization, so we can make custom buttons and remove excess features
- Embedding images with captions using a button (link or upload) or Ctrl+V / context menu paste

### To do 
- [x] Create a preset for Article page that
  - [ ] supports headings & image captions
  - [ ] has limits of 2000 to 63206 characters
- [x] Create a preset for Note page that
  - [ ] doesn't support headings or image captions
  - [ ] has limits of **???**

**Comment by SergeOlabin** [comment]
also implement the configs & toolbar for note and preview
