### ISSUE TITLE
Change post types, fix filters

### ISSUE THREAD

**Issue by calster00** [ita-social-projects/dokazovi-fe#167]
### Task description
Adjust post types to work with changes on BE. 

### To do 
- [x] Change post types to allow for multiple directions
- [x] Fix post cards to fit multiple directions
- [x] Fix repeated expert fetch on Expert Profile
- [x] Fix filters not being reset when user leaves the page (all pages)
