### ISSUE TITLE
Normalize redux state

### ISSUE THREAD

**Issue by calster00** [ita-social-projects/dokazovi-fe#205]
### Task description
Normalize state shape to avoid data duplication across state slices. 
Check out [Normalizr](https://github.com/paularmstrong/normalizr) and [createEntityAdapter](https://redux-toolkit.js.org/api/createEntityAdapter) to see if they fit our needs.

### Todo
- [x] Store post & experts in separate state slice in an object of type `{ [id: string]: entity }`
- [x] Use arrays of ids to reference these entities in any other slice
- [x] Update all slices (thunks) & containers to use new state format
