### ISSUE TITLE
SPIKE #8: CI

### ISSUE THREAD

**Issue by KarkabsisV** [ita-social-projects/dokazovi-fe#34]
### Task description
Make a presentation about CI and how to implement it.

### To do 

- [x] Make a presentation about CI 
- [x] How to implement CI (frontend)
- [x] How to implement CI (backend)

P.S.: Don`t forget about SonarCloud
