### ISSUE TITLE
Newest: sync with BE

### ISSUE THREAD

**Issue by SergeOlabin** [ita-social-projects/dokazovi-fe#67]
### Task description
Sync Important section with BE endpoint

### To do 
- [x] Data to the newest section is fetched from the BE 
- [x] Use axios to perform the request
- [x] use thunk action to perform the request 
- [x] use redux to store the data
- [x] use redux to get the data to the container component

### Estimation
[PERT-Sprint 2](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=212800467)
