### ISSUE TITLE
Direction: Direction page + Experts

### ISSUE THREAD

**Issue by SergeOlabin** [ita-social-projects/dokazovi-fe#68]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/14

### Task description
Create the direction page. header and experts.

### To do 
- [x] Direction Page - use router hook to get the direction itself e.g. covid-19
- [x] Display header title
- [x] extract ExpertsView from Main to reuse in Direction
- ExpertsView -> to render experts from props
- MainExpertsContainer -> to get experts on the Main Page
- [x] Show experts, reuse presentational component from the main view.
- [x] load the data from the BE
- [x] use axios to perform a GET request
- [x] use redux store to perform a fetch action, store and get the data to the component

### Estimation
[PERT-Sprint 2](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=212800467)
