### ISSUE TITLE
Direction - Materials

### ISSUE THREAD

**Issue by SergeOlabin** [ita-social-projects/dokazovi-fe#69]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/22

### Task description
Show materials for the direction.

### To do 
- [x] Reuse view from the MainView, from _NewestContainer_:
  - [x] PostsGridView (new) - to render posts from props
  - [x] NewestContainer (old/existing one) - to get the posts from the store and send to PostsGridView 
- [x] Get materials for the direction
- [x] use axios to perform the request
- [x] use redux to perform an action to fetch and store the data 
- [x] LoadMore works
- [x] use separate thunk action to load the data (depending on the page)
- [x] add spinner for loading data
- [x] scroll to the last fetched row of the data

### Estimation
[PERT-Sprint 2](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=212800467)
