### ISSUE TITLE
Direction - filters for materials

### ISSUE THREAD

**Issue by SergeOlabin** [ita-social-projects/dokazovi-fe#70]
**Story link**
https://github.com/ita-social-projects/dokazovi-be/issues/22

### Task description
Filters section for the materials

### To do 
 - [x] https://github.com/ita-social-projects/dokazovi-fe/issues/69 is DONE
 - [x] use https://react-hook-form.com/ if possible
 - [x] GET request for entity types (Стаття, Допис ...) 
 - [x] GET request for tags
 - [x] use axios for GET requests 
 - [x] use redux to perform an action, store and get the data to the components.
 FILTERS:
 - [x] post types and tags are treated as a form components 
 - [x] on form state change - send a request to GET the updated data.
 - [x] filters are used as query params.
 - [x] use debounceTime for form state change - 500ms

### Estimation
[PERT-Sprint 2](https://docs.google.com/spreadsheets/d/14mClU39kUN25wvr-Di8eQHsuGhzPKMSsjcoCICIQJzU/edit#gid=212800467)
